CREATE TABLE Task (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      title VARCHAR(30) NOT NULL,
                      description TEXT NOT NULL,
                      PRIMARY KEY (id)
);