CREATE TABLE Log (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      description VARCHAR(30) NOT NULL,
                      created_at date NOT NULL,
                      updated_at date NOT NULL,
                      PRIMARY KEY (id)
);